### ISSUE TITLE
Exit code when running task

### ISSUE THREAD

**Issue by eskaaren** [RexOps/Rex#761]
Rex exits with 0 which means success when in fact a SSH connection has failed and the task is not run. This means that also Jenkins jobs will succeed when using Rex even if it really failed.

From CLI.pm around line 585
```perl
  if ($@) {

    # this is always the child
    Rex::Logger::info( "Error running task/batch: $@", "warn" );
    CORE::exit(0);
  }
```

Should perhaps be:
```perl
  if ($@) {

    # this is always the child
    Rex::Logger::info( "Error running task/batch: $@", "error" );
    CORE::exit(1);
  }
```

**Comment by kablamo** [comment]
There are a couple problems here.  

1. First of all, I don't think this if block should exist.  Long term, we should delete it.  Children should exit earlier.  That probably won't happen soon because its hard to verify all the logic.

2. This block definitely should not get executed when an ssh connection fails.  I've been cleaning up some of the forking code and it no longer happens in my branch here: https://github.com/RexOps/Rex/pull/697

3. Even with my fix, I still see an exit status of 0.  After debugging I have discovered that if you do:
```
exit 65820
```
perl will exit with a status of 0!  I did not expect that.

**Comment by kablamo** [comment]
ok apparently exit codes can only be 8 bits.  The 65820 came from `$?` when a coderef died.  Instead of using `$?` I think we should use `$? >> 8`.  That gives me 255.

http://stackoverflow.com/questions/32292101/why-does-exit65280-cause-perl-to-exit-with-an-exit-status-of-0

**Comment by kablamo** [comment]
Ok I fixed this in my branch #697.  Here is the commit:
https://github.com/kablamo/Rex/commit/d0b67aed2480311b51fe9b1a505050cd437cbc22

**Comment by ferki** [comment]
@kablamo: it looks like I still get an exit code of `0` when the SSH connection fails and/or when I run something simple to fail (e.g. `rex -e 'run "abcdef"'`).

**Comment by kablamo** [comment]
Thanks for finding these.  The exit code stuff has never worked with `-e`.  Not sure whats up with the SSH connection thing yet.  Am working on a pr to fix both of these.

**Comment by ferki** [comment]
@eskaaren: I believe the isse originally reported here (`SSH connection has failed and the task is not run`) has been solved on #697, and the exit codes for one-liners (= using `-e` on the CLI) has been resolved on #840. So to reduce the number of open issues/PRs around this topic, I chose to close this one. Feel free to reopen if you think something has been missed.

There are two remaining smaller known issues with exit codes (exit code when no Rexfile is present, and exit code when a non-existing task is called), and they are tracked on #400.
